site_name: זעם ברחבי ישראל

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: he
  palette: 
    scheme: slate
    primary: brown
    accent: red
  font:
    text: IBM Plex Sans Hebrew
  