site_name: זעם ברחבי ישראל

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: he
  palette: 
    scheme: slate
    primary: brown
    accent: red
  font:
    text: IBM Plex Sans Hebrew

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - pymdownx.snippets